---
name: Publish Release

on:
  pull_request:
    branches:
      - master

  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          useConfigFile: true

      - name: Changelog
        uses: Bullrich/generate-release-changelog@master
        id: generate_changelog
        env:
          REPO: ${{ github.repository }}
        if: github.ref_name == 'master'

      - name: Publish Github Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.gitversion.outputs.MajorMinorPatch }}
          name: ${{ steps.gitversion.outputs.MajorMinorPatch }}
          body: |
            ${{ steps.generate_changelog.outputs.changelog }}

            A new version **${{ steps.gitversion.outputs.MajorMinorPatch }}** for the **ansible-infra-deprovisioning** role was generated automatically through the **ansible-infra-deprovisioning** workflow.
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
        if : github.ref_name == 'master'
